# Some colored makepkg-like functions
msg_blue()
{
  printf "${BLUE}==>${ALL_OFF}${BOLD} ${1}${ALL_OFF}\n"
}

note_blue()
{
  printf "${BLUE}==>${ALL_OFF}${BOLD} NOTE${1}:${ALL_OFF} ${2}\n"
}

ALL_OFF="$(tput sgr0)"
BOLD="$(tput bold)"
BLUE="${BOLD}$(tput setaf 4)"
GREEN="${BOLD}$(tput setaf 2)"

post_install()
{
  echo
  msg_blue "To use the pretrained models, add the following environment variable:"
  msg_blue "   MODEL_PATH='/opt/spleeter-data'"
  echo
}

post_upgrade()
{
  post_install
}
