post_install() {
  _pkgname=ExifCleaner
  pkgname=exifcleaner

  # Link to the binary
  ln -sf "/opt/$_pkgname/$pkgname" "/usr/bin/$pkgname"

  # SUID chrome-sandbox for Electron 5+
  chmod 4755 "/opt/$_pkgname/chrome-sandbox" || true

  update-mime-database /usr/share/mime || true
  update-desktop-database /usr/share/applications || true
}

post_remove() {
  pkgname=exifcleaner

  # Delete the link to the binary
  rm -f "/usr/bin/$pkgname"
}
