#!/usr/bin/env sh

# mangle replaces directive
sed -E -e 's&^(\s*)(replaces\+?=)&\1 _ignore_\2&g' -i PKGBUILD

# don't make -docs
sed -E \
  -e 's&^(\s*)(.*make htmldocs)$&\1 : # \2&' \
  -e '/^\s*"\$.*-docs.*"$/d' \
  -i PKGBUILD

# rename pkgbase
sed -E \
  -e 's&^(pkgbase=\S+)(.*)$&\1-x64v3&' \
  -i PKGBUILD
