---
update-tools:
  stage: process
  image: alpine:latest
  script:
    - apk add bash
    - bash .tools/update-tools.sh
  resource_group: chaotic
  needs: ["on-schedule"]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $SCHEDULED == "1"
