#Type Path                                 Mode User Group   Age Argument
f     /run/crond.reboot                    0644 root root    -   -
f     /run/crond.bootdir                   0644 root root    -   -
z     /usr/lib/systemd-cron/crontab_setgid 2755 root crontab -   -
d     /var/spool/cron                      1730 root crontab -   -

