#!/bin/sh
unset JFXPATH

if [ -e /usr/lib/jvm/java-17-openjfx/lib/javafx.base.jar ]; then
        JFXPATH=/usr/lib/jvm/java-17-openjfx/lib
else
        JFXPATH=/usr/lib/jvm/java-17-openjdk/lib
fi

CP="/opt/bluej/boot.jar"
JAVAFXJARS=`ls -1 $JFXPATH/javafx* | paste -sd ":" -`
#JAVAFXJARS=`ls -1 /opt/bluej/javafx* | paste -sd ":" -`
CP="$CP:$JAVAFXJARS"

archlinux-java-run -a 17 -b 17 -- \
	-Djdk.gtk.version=2 \
        -Dawt.useSystemAAFontSettings=on -Xmx512M \
        -cp "$CP" bluej.Boot \
        "$@"
