version = 1

[[annotations]]
path = [
    ".gitignore",
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "shader-slang-8369.patch",
]
SPDX-FileCopyrightText = "shader-slang contributors"
SPDX-License-Identifier = "Apache-2.0"
