#!/usr/bin/env bash

_check_update() {
  local url pkgver pkgrel _pkgver _response _tag _pkgver_new

  eval "$(grep -Eo '^(url|pkgver|pkgrel)=\S+' PKGBUILD)"
  _pkgver=$(LANG=C LC_ALL=C pacman -Si chaotic-aur/pixelorama | grep -Pom1 '^Version\s+:\s+\K\S+')

  CI_PACKAGE_BUMP="$_pkgver"
  eval "$(grep -Eom1 '^CI_PACKAGE_BUMP=\S+$' .CI/config | sed 's&/&.&g')"

  _response=$(curl -Ssf "$url/releases")
  _tag=$(
    printf '%s' "$_response" \
      | grep -E '/tag/v([0-9\.]+)"' \
      | sed -E 's&^.*/tag/v([0-9\.]+)".*$&\1&' \
      | sort -rV | head -1
  )
  _pkgver_new="${_tag#v}"

  if [ $(vercmp "${_pkgver_new:?}" "$_pkgver") -gt 0 ]; then
    echo "New upstream release.  $_pkgver_new > $_pkgver"
  elif [ $(vercmp "${pkgver:-0}-${pkgrel:-0}" "${_pkgver:-a}") -gt 0 ]; then
    echo "New PKGBUILD.  ${pkgver}-${pkgrel} > $_pkgver"
  elif [ $(vercmp "$CI_PACKAGE_BUMP" "$_pkgver") -gt 0 ]; then
    echo "Bumped.  $CI_PACKAGE_BUMP > $_pkgver"
  else
    return $CI_CODE_SKIP
  fi
}

_check_update || return $?
