#!/usr/bin/env bash

_check_update() {
  local _url _remote _regex _pkgver_new _pkgver_old
  _url="https://salsa.debian.org/installer-team/console-setup"
  _remote=$(git ls-remote "$_url.git")
  _regex='^.*/tags/([0-9\.]+)$'
  _pkgver_new=$(
    printf '%s' "$_remote" \
      | grep -E "$_regex" \
      | sed -E 's&'"$_regex"'&\1&' \
      | sort -rV | head -1
  )

  _pkgver_old=$(LANG=C LC_ALL=C pacman -Si "chaotic-aur/ckbcomp" | grep -Pom1 '^Version\s+:\s+\K\S+(?=-[0-9])')

  if [ $(vercmp "$_pkgver_old" "${_pkgver_new:?}") -ge 0 ]; then
    echo "Skipping build.  $_pkgver_old >= $_pkgver_new"
    return "$CI_CODE_SKIP"
  fi
}

_check_update || return $?
