#!/usr/bin/env bash

_check_rate() {
  local _rate _date_build _epoch_build _epoch_now _epoch_diff

  _rate="$((3600 * ${1:-18}))" # hours
  _date_build="$(LC_ALL=C pacman -Si chaotic-aur/freecad-git | grep -Pom1 '^Build Date\s+:\s+\K\S.*\S$')"
  _epoch_build=$(\date '+%s' -d "$_date_build")
  _epoch_now=$(\date '+%s')
  _epoch_diff="$((_epoch_now - _epoch_build))"

  if [[ "$_epoch_diff" -lt "$_rate" ]]; then
    echo "Heavy package.  Skipping build."
    echo "> Last built $((_epoch_diff / 3600)) hours ago."
    return $CI_CODE_SKIP
  fi
}

_check_bump() {
  local url pkgver pkgrel _pkgver

  eval "$(grep -Eo '^(url|pkgver|pkgrel)=\S+' PKGBUILD)"
  _pkgver=$(LC_ALL=C pacman -Si chaotic-aur/freecad-git | grep -Pom1 '^Version\s+:\s+\K\S+')

  CI_PACKAGE_BUMP="$_pkgver"
  eval "$(grep -Eom1 '^CI_PACKAGE_BUMP=\S+$' .CI/config | sed 's&/&.&g')"

  if [ $(vercmp "${pkgver:-0}-${pkgrel:-0}" "${_pkgver:-a}") -gt 0 ]; then
    echo "New PKGBUILD.  ${pkgver}-${pkgrel} > $_pkgver"
  elif [ $(vercmp "$CI_PACKAGE_BUMP" "${_pkgver:-a}") -gt 0 ]; then
    echo "Bumped.  $CI_PACKAGE_BUMP >= $_pkgver"
  else
    return 2
  fi
}

_check_status() (
  local url _url_ci _commit _response _msg_err _success_ci
  eval "$(grep -Eo '^(url)=\S+' PKGBUILD)"

  _commit=$(git ls-remote "$url.git" HEAD 2>/dev/null | grep -m1 -oP '\w+(?=\t\w)')
  _url_ci="$url/commit/$_commit/checks"
  _response=$(curl -Ssf "$_url_ci")
  _success_ci=false

  if grep -qo 'favicon-success.svg' <<<"$_response"; then
    _msg_err="Check-in success."
    _success_ci=true
  elif grep -qo 'favicon-failure.svg' <<<"$_response"; then
    _msg_err="Error: Check-in failed."
    _success_ci=false
  else
    _msg_err="Error: Check-in incomplete."
    _success_ci=false
  fi

  echo "$_msg_err"
  echo "> $_url_ci"

  if [ "${_success_ci::1}" != "t" ]; then
    return "$CI_CODE_SKIP"
  fi
)

_check_bump || _check_rate 24 || return $?
#_check_status || return $?
