#!/usr/bin/env sh

# mangle replaces directive
sed -E -e 's&^(\s*)(replaces\+?=)&\1 _ignore_\2&g' -i PKGBUILD

# don't make -docs
sed -E \
  -e 's&^(\s*)(.*make htmldocs)$&\1 : # \2&' \
  -e '/^\s*"\$.*-docs.*"$/d' \
  -e 's&"\$\S*-docs"&&g' \
  -i PKGBUILD

# remove 32-bit support
sed -E \
  -e '/vim:set/q' \
  -e 's&\b(pentium4|i686|i486)\b&&g' \
  -i PKGBUILD
