#!/usr/bin/env sh

# mangle license spam
sed -E -e 's&^(\s*)(license\+?=)&\1 _ignore_\2&g' -i PKGBUILD

# don't make -docs
sed -E \
  -e 's&^(\s*)(.*make htmldocs)$&\1 : # \2&' \
  -e '/^\s*"\$.*-docs.*"$/d' \
  -e 's&"\$\S*-docs"&&g' \
  -i PKGBUILD
