[wsjtx-improved-qt6]
source = "regex"
url = "https://sourceforge.net/projects/wsjt-x-improved/files/"
regex = '[Ww][Ss][_-]([0-9.]+[-a-z0-9]*_[0-9]+)'
from_pattern = '([0-9.]+)(-win64)?_([0-9]+)'
to_pattern = '\1+\3'
