---
name: "👶 Request to add new package"
description: "Request to add new package"
labels: ["request:new-pkg"]
title: "[Request] package_name"
body:
  - type: textarea
    attributes:
      label: "Package"
      description: |
        Link to the package base in the AUR.  Include any known AUR dependencies.
        If a relevant issue already exists, please comment instead of opening a new one.
      value: |
        https://aur.archlinux.org/pkgbase/package_name
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Purpose"
      description: |
        What does the package do?  How is it used?  How is it useful?
        What specific benefits does this package have over other packages (eg, stable vs git)?
        Why would a user use this package instead of another?
        What are some use cases for this package?
    validations:
      required: true
  - type: textarea
    attributes:
      label: "License"
      description: |
        What is the name of the copyright license?
        Packages with licenses that prohibit redistribution will be rejected.
        Only the name is needed for standard licenses, like GPL-2.0-only.
        Include link for non-standard licenses and EULA.
      value: |
        GPL-3.0-or-later
    validations:
      required: true
  - type: checkboxes
    id: presubmission
    attributes:
      label: Submission checklist
      description: |
        Before submitting this request, please ensure:
      options:
        - label: The package is not banned.
          required: true
        - label: The package is not available in Chaotic AUR or official Arch repos.
          required: true
        - label: The package has not already been requested.
          required: true
