---
name: "Request rebuild 🏗️ / Report bugs 🐛"
description: "Report bugs or request to rebuild package."
labels: ["request:rebuild-pkg"]
title: "[Rebuild] package_name"
body:
  - type: textarea
    attributes:
      label: "Packages"
      description: |
        Link to the package bases in the AUR.
        Please ensure that the AUR package has already been updated before reporting.
        If a relevant issue already exists, please comment instead of opening a new one.
      value: |
        https://aur.archlinux.org/pkgbase/package_name
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Description"
      description: |
        Why does this package need to be rebuilt?
      value: |
        Broken?  Missing?  Outdated?  Etc.
        Include details, such as error messages, to aid troubleshooting.
        Include current and latest versions for outdated packages.
    validations:
      required: true
