name: "👴 Report outdated package"
description: "Report outdated package"
labels: ["request:rebuild-pkg"]
title: "[Outdated] packagename"
body:
  - type: textarea
    attributes:
      label: "Packages:"
      description: "Link to the package bases in the AUR.
        <br/> Please ensure that the AUR has been updated before reporting."
      placeholder: "[packagenamehere](https://aur.archlinux.org/pkgbase/packagenamehere)"
    validations:
      required: true
  - type: input
    attributes:
      label: "Latest chaotic version"
      placeholder: "`v0.0.0.r0.gc0ffec0ffe`"
    validations:
      required: true
  - type: input
    attributes:
      label: "Latest upstream version"
      placeholder: "`v1.0.0.r100.gdeadbeef`"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Logs"
      description: "If available.  Find them here: https://builds.garudalinux.org/repos/chaotic-aur/logs/"
      placeholder: "https://builds.garudalinux.org/repos/chaotic-aur/logs/some-package.log"
  - type: textarea
    attributes:
      label: "Builds in clean chroot?"
      description: "https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot"
      placeholder: "If you have built this package, type the commands you used.

        If any special procedures were needed, please describe them."
  - type: textarea
    attributes:
      label: "More information"
