name: "👶 New package requests"
description: "Request a new package"
labels: ["request:new-pkg"]
title: "[Request] "
body:
  - type: textarea
    attributes:
      label: "Link to the package(s) in the AUR"
      placeholder: "[insert the link here](https://example.com)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Utility this package has for you"
      description: "This is the place to describe how you use the package and how it can be helpful."
  - type: dropdown
    attributes:
      label: "Do you consider the package(s) to be useful for every Chaotic-AUR user?"
      options:
        - "YES!"
        - "No, but for a great amount."
        - "No, but for a few."
        - "No, it's useful only for me."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Do you consider the package to be useful for feature testing/preview?"
      description: "e.g: mesa-aco, wine-wayland"
      options:
        - label: "Yes"
  - type: checkboxes
    attributes:
      label: "Are you sure the package isn't available already?"
      description: "test with `pacman -Ss <pkgname>`"
      options:
        - label: "Yes"
          required: true
    attributes:
      label: "Have you tested if the package builds in a clean chroot?"
      description: "https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot"
      options:
        - label: "Yes"
  - type: dropdown
    attributes:
      label: "Does the package's license allow redistributing it?"
      options:
        - "YES!"
        - "No clue."
        - "No, but the author doesn't really care anyways. It's just for bureaucracy."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Have you searched the issues to ensure this request is unique?"
      description: "https://github.com/chaotic-aur/packages/issues"
      options:
        - label: "YES!"
          required: true
  - type: checkboxes
    attributes:
      label: "Have you read the README to ensure this package is not banned?"
      description: "https://github.com/chaotic-aur/packages#banished-and-rejected-packages"
      options:
        - label: "YES!"
          required: true
  - type: textarea
    attributes:
      label: "More information"
