name: "👴 Reporting outdated packages"
description: "Request an outdated package"
labels: ["request:rebuild-pkg"]
title: "[Outdated] "
body:
  - type: textarea
    attributes:
      label: "If available, link to the latest build"
      description: "Find it here: https://builds.garudalinux.org/repos/chaotic-aur/logs/"
      placeholder: "[some-package.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/some-package.log)"
  - type: input
    attributes:
      label: "Package name"
      placeholder: "`some-package`"
    validations:
      required: true
  - type: input
    attributes:
      label: "Latest build"
      placeholder: "`v0.0.0.r0.gc0ffec0ffe`"
    validations:
      required: true
  - type: input
    attributes:
      label: "Latest version available"
      placeholder: "`v1.0.0.r100.gdeadbeef`"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Have you tested if the package builds in a clean chroot?"
      options:
        - label: "Yes"
  - type: textarea
    attributes:
      label: "More information"
