post_install() {
  cat <<EOF
>>> Enable a cron daemon such as cronie or use the included systemd user units in
/usr/share/backintime/contrib/ in order to get backintime scheduling to work
EOF
}

post_upgrade() {
  if [ "$(vercmp "$2" 1.6.1-2)" -lt 0 ]; then
  cat <<EOF
>>> WARN: /usr/share/backintime/contrib/backintime-backup-job.service has changed!
    Diff user unit against this or backups will not trigger!
EOF
  fi
}
