# sway does not set DISPLAY/WAYLAND_DISPLAY in the systemd user environment
# See FS#63021
# Adapted from xorg's 50-systemd-user.sh, which achieves a similar goal.

# Upstream refuses to set XDG_CURRENT_DESKTOP so we have to.
# These systemctl calls need to be in one exec command, otherwise some services
# might try to start before the environment variables are available.
exec systemctl --user set-environment XDG_CURRENT_DESKTOP=sway && \
     systemctl --user import-environment DISPLAY \
                                         SWAYSOCK \
                                         WAYLAND_DISPLAY \
                                         XDG_CURRENT_DESKTOP && \
     systemctl --user start sway-session.target

exec swaymsg -t subscribe '["shutdown"]' && systemctl --user stop sway-session.target

exec hash dbus-update-activation-environment 2>/dev/null && \
     dbus-update-activation-environment --systemd DISPLAY \
                                                  SWAYSOCK \
                                                  XDG_CURRENT_DESKTOP=sway \
                                                  WAYLAND_DISPLAY
