post_install() {
  echo -e "\n  Read the .service file if you encounter any edge cases"
  echo -e "\n  1. Do not store your media directory or download directory in /home"
  echo -e "  2. LXC users override the service with PrivateUsers=false"
  echo -e "  3. This package now comes with a shared group media'"
  echo -e "     Override if necessary."
  echo -e "\n  Overriding is done with \`systemctl edit radarr\`\n"
}

post_upgrade() {
  post_install "${1}"
}
