version = 1

[[annotations]]
path = [
    ".SRCINFO",
    ".gitignore",
    ".nvchecker.toml",
    "PKGBUILD",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "vim-keybindings.patch",
]
SPDX-FileCopyrightText = "htop-vim contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"
