#!/bin/sh

opts=(
  -Dswing.crossplatformlaf='com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
  -Dawt.useSystemAAFontSettings='on'
  -Dswing.aatext='true'
)

exec /usr/bin/java "${opts[@]}" -jar '/usr/share/java/bytecodeviewer/bytecodeviewer.jar' "$@"
