post_install() {
    echo "This version of clion has no bundled JRE."
    echo "See https://www.jetbrains.com/help/clion/switching-boot-jdk.html for"
    echo "instructions on configuring clion to use an external JRE."
}

post_upgrade() {
    echo "This version of clion has no bundled JRE."
    echo "See https://www.jetbrains.com/help/clion/switching-boot-jdk.html for"
    echo "instructions on configuring clion to use an external JRE."
}
