#!/bin/bash
# A script to run Presentations.
ext="${@##*.}"
shopt -s nocasematch
case "$ext" in
	"prs" ) /usr/share/office2024/presentations -S\""$@"\";;
	"pps" ) /usr/share/office2024/presentations -S\""$@"\";;
	"ppsx" ) /usr/share/office2024/presentations -S\""$@"\";;
	* ) /usr/share/office2024/presentations "$@";;
esac
