#!/usr/bin/env sh

_check_update() {
  local _snapname _response _pkgver_new _pkgver_old
  _snapname="termius-app"
  _response=$(
    curl -H 'Snap-Device-Series: 16' --no-progress-meter "http://api.snapcraft.io/v2/snaps/info/$_snapname" \
      | sed 's@,@,\n@g'
  )
  _pkgver_new=$(
    printf '%s' "$_response" \
      | grep '"version"' \
      | sed -E 's@^"version":"([0-9]+\.[0-9]+\.[0-9]+)".*$@\1@' \
      | head -1
  )

  _pkgver_old=$(LANG=C LC_ALL=C pacman -Si chaotic-aur/termius | grep -Pom1 '^Version\s+:\s+\K\S+(?=-[0-9])')

  if [ $(vercmp "$_pkgver_old" "${_pkgver_new:?}") -ge 0 ]; then
    echo "Skipping build.  $_pkgver_old >= $_pkgver_new"
    return "$CI_CODE_SKIP"
  fi
}

_check_update || return $?
