# Maintainer:

_pkgname="das-keyboard-q"
pkgname="$_pkgname"
pkgver=4.3.0
pkgrel=1
pkgdesc="Software for Das Keyboard 5Q, 5Qs, 4Q"
url="https://www.daskeyboard.io/get-started/software/"
license=('LicenseRef-Unknown')
arch=('x86_64')

options=('!debug')

_pkgsrc="$_pkgname-$pkgver"
_pkgext="deb"
source=("$_pkgsrc.$_pkgext"::"https://das-keyboard-q-releases.s3.us-east-2.amazonaws.com/das-keyboard-q/linux/x64/das-keyboard-q_${pkgver}_amd64.$_pkgext")
sha256sums=('1a065d5ebd751d26ef96a957e051274fba0bb10df43596b1edd70deafbacd319')

package() {
  depends+=(
    alsa-lib
    at-spi2-core
    bash
    cairo
    dbus
    expat
    glib2
    gtk3
    libcups
    libdrm
    libx11
    libxcb
    libxcomposite
    libxdamage
    libxext
    libxfixes
    libxkbcommon
    libxrandr
    mesa
    nspr
    nss
    pango
  )

  tar xf data.tar.zst -C "$pkgdir"

  install -Dm644 "$pkgdir/usr/lib/das-keyboard-q/resources/extra_resources/scripts/70-daskeyboard.rules" -t "$pkgdir/usr/lib/udev/rules.d/"

  # unwanted
  rm -rf "$pkgdir"/usr/share/{doc,lintian}

  # disable scripts
  for i in "$pkgdir/usr/lib/das-keyboard-q/resources/extra_resources/scripts"/*.sh; do
    install -Dm755 /dev/stdin "$i" << END
#!/usr/bin/env sh

# This script was disabled during packaging.
# Notify the package maintainers if there are any problems.
END
  done

  # may still be needed, based on contents of createRules.sh
  install -Dm644 /dev/stdin "$pkgdir"/etc/udev/rules.d/99-daskeyboard.rules << END
# Do not edit this file.  It will be overwritten when aur/das-keyboard-q is upgraded.
#
# The purpose of this file is to prevent das-keyboard-q from creating incorrect rules.
# The real rules are at /usr/lib/udev/rules.d/70-daskeyboard.rules
END

  # permissions, remove sticky bit
  chmod -R u+rwX,go+rX,go-ws,u-s "$pkgdir/"
}
