post_install() {
	setcap 'CAP_SYS_RESOURCE=+ep' usr/bin/noisetorch

    # Disclaimer about a potential compromise of the source code
    echo "NOTE: The original developer can not guarantee the security of the code of versions before 0.11.6. Additionally development has shifted to a new repository."
    echo "The current codebase has been audited by the community, as can be seen here: https://github.com/noisetorch/NoiseTorch/discussions/275"
}

post_upgrade() {
	post_install "$1"
}
