[whisparr-nightly-bin]
source = "git"
git = "https://github.com/Whisparr/Whisparr"
prefix = "v"
exclude_regex = "^v3\\..*|.*-release.*"
from_pattern = "(\\d\\.\\d\\.\\d)-develop(\\.\\d+)"
to_pattern = "\\1.develop\\2"
