# Maintainer: Yiyao Yu <yuydevel at protonmail dot com>
# Contributor: Erik Dubois <erik.dubois@gmail.com>
pkgname=surfn-icons-git
_pkgname=Surfn
pkgver=26.06.21.r7.g1f8dde7b
pkgrel=2
epoch=1
pkgdesc='Surfn, a colourful base icon theme'
arch=('any')
url='https://github.com/erikdubois/Surfn'
license=('CC-BY-NC-SA-4.0')
makedepends=('git')
options=(!strip !emptydirs)
install=surfn-icons-git.install
source=('Surfn::git+https://github.com/erikdubois/Surfn.git')
sha256sums=('SKIP')

pkgver() {
  cd "${_pkgname}"
  git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}

package() {
  cd "${srcdir}/${_pkgname}/usr/share/icons"

  # Delete build scripts and caches regenerated by the system icon-cache hook.
  find "${_pkgname}" -type f \( -name '*.sh' -o -name 'icon-theme.cache' \) -delete

  install -dm 755 "${pkgdir}/usr/share/icons/"
  cp -r "${_pkgname}" "${pkgdir}/usr/share/icons/"
}

# vim:set et ts=2 sw=2 tw=79:
