#!/bin/bash -e

die() {
  echo >&2 "$@"
  exit 1
}

(( $# >= 2 )) || die "Usage: $0 TOKEN-FILE SYMBOL-ARCHIVE..."
token="$1"
shift

[[ -f $token && -s $token ]] || die "Invalid TOKEN-FILE ${token@Q}"

for archive; do
  [[ $(file -Ebi "$archive") == application/zip* ]] || die "Invalid SYMBOL-ARCHIVE ${archive@Q}"
done

for archive; do
  echo >&2 "Uploading ${archive@Q} ..."
  curl -X POST -H "Auth-Token: $(<"$token")" -F "${archive##*/}=@$archive" \
    --retry 4 --retry-connrefused --connect-timeout 120 \
    https://symbols.mozilla.org/upload/
  echo
done
