#!/usr/bin/env bash

_check_status() (
  local _url_repo _url_ci _commit _response _status _msg_err _success_ci
  _url_repo="https://gitlab.gnome.org/GNOME/gimp"
  _commit=$(git ls-remote "$_url_repo.git" HEAD 2>/dev/null | grep -m1 -oP '\w+(?=\t\w)')
  _url_ci="$_url_repo/-/commit/$_commit/pipelines.json"
  _response=$(curl -Ssf "$_url_ci")

  _status=$(grep -Eom1 '"details":{"status":{"icon":"[a-z_]+"' <<< "$_response")

  if grep -qo status_success <<< "$_status"; then
    _msg_err="Check-in status: Success."
    _success_ci=true
  elif grep -qo status_failed <<< "$_status"; then
    _msg_err="Check-in status: Failed."
    _success_ci=false
  elif grep -qo status_running <<< "$_status"; then
    _msg_err="Check-in status: Incomplete."
    _success_ci=false
  else
    _msg_err="Check-in status: Unknown."
    _success_ci=false
  fi

  echo "$_msg_err"
  echo "> $_url_ci"

  if [ "${_success_ci::1}" != "t" ]; then
    return "$CI_CODE_SKIP"
  fi
)

_check_status || return $?
