post_install() {
	echo ":: The Neovim executable is called 'nvim'."
	echo ":: If you are already familiar with Vim, see ':help nvim-from-vim'"
	echo "   to get started."
	echo ":: If you have any questions, check the following page first:"
	echo "   https://github.com/neovim/neovim/wiki/FAQ"
}

post_upgrade() {
	echo ":: Check the following page to see whether this upgrade"
	echo "   includes any breaking changes:"
	echo "   https://github.com/neovim/neovim/wiki/Following-HEAD"
}
