PKGVER="$(ls /usr/src/ | grep 'asus_fan' | cut -d '-' -f 2)"
_dkms="/usr/bin/dkms"


post_install() {
  ${_dkms} add -m "asus_fan/${PKGVER}"
  ${_dkms} build -m "asus_fan/${PKGVER}"
  ${_dkms} install -m "asus_fan/${PKGVER}"

  echo "Enabling asus-fan as service in systemd"
  systemctl enable asus-fan.service
}

post_upgrade() {
  post_install
}

pre_remove() {
  ${_dkms} remove -m "asus_fan/${PKGVER}" --all
}

pre_upgrade() {
  pre_remove
}

post_remove() {
  depmod -a
}

