# Colored makepkg-like functions
msg_blue() {
  printf "${BLUE}==>${BOLD} $1${ALL_OFF}\n"
}

warn1() {
  printf "${BLUE}==>${YELLOW} WARNING:${BOLD}${WHITE} $1${ALL_OFF}\n"
}

warn2() {
  printf "${BLUE}==>         ${BOLD}${WHITE} $1${ALL_OFF}\n"
}

ALL_OFF="$(tput sgr0)"
BOLD="${ALL_OFF}$(tput bold)"
BLACK="${BOLD}$(tput setaf 0)"
RED="${BOLD}$(tput setaf 1)"
GREEN="${BOLD}$(tput setaf 2)"
YELLOW="${BOLD}$(tput setaf 3)"
BLUE="${BOLD}$(tput setaf 4)"
MAGENTA="${BOLD}$(tput setaf 5)"
CYAN="${BOLD}$(tput setaf 6)"
WHITE="${BOLD}$(tput setaf 7)"

post_install() {
  warn1 "mercury-browser has not yet been updated for CVE-2024-9680."
  warn2 'There have been "reports of this vulnerability being exploited'
  warn2 'in the wild."  Users are strongly advised to switch to another'
  warn2 'browser.  For more information, see the following:'
  warn2
  warn2 '   https://www.mozilla.org/en-US/security/advisories/mfsa2024-51'
  warn2 '   https://github.com/Alex313031/Mercury/issues/227'
}


post_upgrade() {
  post_install
}
